### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/permanent-sdk#3]
As described in [our initial SDK thoughts](https://pad.opentechstrategies.com/p/permanent-sdk-thoughts) this SDK will be functional, and one of the first functions we need to implement is authentication.

I'm not sure if this will mean actually supporting full blown authentication (e.g. passing a username + password) or if it will instead involve requiring the developer to generate a bearer token and pass it.

We may want:

* Some kind of `authenticate` method.
* TypeScript types related to whatever Authentication object our core SDK methods needs to accept
* Some kind of `verifyToken` method (name is not perscriptive) which confirms that a given set of credentials are valid.

**Comment by jasonaowen** [comment]
I learned a few things from working on https://github.com/PermanentOrg/node-sdk/pull/37, both about requirements and about approaches.

First, clients need a way to serialize and deserialize tokens; there are use cases where we cannot keep the token in memory for the lifetime of the token. Similarly, clients allowed to request refresh tokens from FusionAuth will need a way to refresh those tokens.

One of the open questions here is how much responsibility the SDK should take, and how much it should leave to the client application. If we take over some of the responsibility for obtaining tokens, we will need to provide hooks for going through the authorization code workflow: get the URL to redirect to, and complete the workflow when the IdP redirects back to the client application.

The very simplest thing the SDK can do is nothing: obtaining a token is purely up to the client, and each SDK function takes a token as an argument. The OAuth library the client selects can take care of requesting tokens, token validation (at least against token expiration), refresh tokens, and persistence. The main advantage of this approach is that it is very easy to implement, and as a maybe bonus, it stays out of the way of any client-specific token management.

On the other end of the spectrum, the SDK can be opinionated almost to the point of being opaque: we select an OAuth library (almost certainly [simple-oauth2](https://www.npmjs.com/package/simple-oauth2)), we include a CSRF token in initiating the authorization code flow, validate it after the redirect, and provide de/serialization and refresh methods along with accompanying type definitions.

I think it may make sense to start out on the minimalist end of the spectrum. OAuth is a well-understood problem, there are solid options for dealing with it, and it's not obvious to me that attempting to shoulder that responsibility in the SDK would be unambiguously more helpful than hurtful.

Side note:

> e.g. passing a username + password

It will certainly not be this. No client should ever ask the user for password credentials, Permanent should not allow any FusionAuth clients to use the resource owner password flow, and the SDK should not have any code that even suggests this as an option. (I do not mean to be harsh here, but I think it is valuable to remove this idea from people's minds!)

**Comment by jasonaowen** [comment]
A more detail-oriented question is: how should clients pass the token to SDK functions? The simplest is to accept the bare token value as a `string`, but with simple-oauth2 that becomes tedious as the client almost certainly needs to hold on to the full token object, so there'd be a bunch of calls like `permanentSdkFunction(token.access_token, ...)` (emphasis on the property access in the middle). We could define a type `{ access_token: string; }` and accept that, but I slightly worry about making it more difficult to use other OAuth libraries and so effectively making a decision on behalf of the client. Probably worth doing some further research on how other libraries handle this.

**Comment by jasonaowen** [comment]
> I think it may make sense to start out on the minimalist end of the spectrum. OAuth is a well-understood problem, there are solid options for dealing with it, and it's not obvious to me that attempting to shoulder that responsibility in the SDK would be unambiguously more helpful than hurtful.

After discussing this with @kfogel and @kavyasukumar, and thinking further, I am going to more strongly recommend that the SDK not be involved with obtaining, persisting, or refreshing tokens, and instead delegate that responsibility to the clients of this SDK. That allows us to proceed more carefully in this repo, as mistakes in libraries can be difficult or painful to change once third parties start using them; and on the other hand, adding such functionality later is easy and safe.

It's not completely obvious to me who has decision-making authority here, so taking inspiration from @slifty's recent reasonable and correct action in moving forward in response to silence, I am going to declare this **decided**.

There is still work to do here: we need to add documentation about this decision, links to further reading about OAuth, and describe how to get application credentials to begin the OAuth workflow with Permanent. See also the [brief documentation we have for the old SDK](https://github.com/PermanentOrg/node-sdk/blob/main/README.md).

**Comment by jasonaowen** [comment]
> A more detail-oriented question is: how should clients pass the token to SDK functions? ... worth doing some further research on how other libraries handle this.

I spent some time looking, and my slightly surprised first answer is that there _aren't_ many other libraries! The main ones I found are the aforementioned simple-oauth2, [angular-oauth2-oidc](https://www.npmjs.com/package/angular-oauth2-oidc), and [client-oauth2](https://www.npmjs.com/package/client-oauth2).

The Angular library wants to be fully responsible for the token AND the requests made using that token; it's not obvious to me how we could structure this SDK to be compatible with that approach. (See also #5, and would love your thoughts @meisekimiu!)

client-oauth2 returns an object that uses `accessToken`, in contrast to simple-oauth2's `access_token`, so for a first pass let's just take a simple `string` and users can pass `token.accessToken` or `token.access_token` as their library of choice dictates.

**Comment by jasonaowen** [comment]
> The Angular library wants to be fully responsible for the token AND the requests made using that token; it's not obvious to me how we could structure this SDK to be compatible with that approach.

Looking more closely, it looks like we'd be able to inject the `OAuthStorage` dependency and then `const token = this.authStorage.getItem('access_token');`. It's not as convenient as the magical interceptor pattern they prefer, but would be a path forward for using that library with this SDK under the approach of passing a `string` token that we include with `fetch` (per https://github.com/PermanentOrg/permanent-sdk/issues/5#issuecomment-1032940421). So that's good news!

**Comment by slifty** [comment]
> After discussing this with @kfogel and @kavyasukumar, and thinking further, I am going to more strongly recommend that the SDK not be involved with obtaining, persisting, or refreshing tokens, and instead delegate that responsibility to the clients of this SDK. That allows us to proceed more carefully in this repo, as mistakes in libraries can be difficult or painful to change once third parties start using them; and on the other hand, adding such functionality later is easy and safe.

Glad you moved forward with this -- sorry for not commenting sooner but if I had I would have made the same suggestion.

We can always add sdk support for auth / token generation in a future, but we're in MVP mode and the path you're suggesting involves no development effort!

If we do explore that down the line: one SDK that does handle auth is the firebase SDK I was poking around before; it has [an auth module](https://github.com/firebase/firebase-js-sdk/tree/master/packages/auth) which may be worth looking at.

@jasonaowen what do you think of having an `Authentication` type that our functions take as first param which contains whatever we deem  necessary to pass around, even if that ends up JUST being a `bearerToken` attribute?

**Comment by jasonaowen** [comment]
> having an `Authentication` type that our functions take as first param which contains whatever we deem necessary to pass around, even if that ends up JUST being a `bearerToken` attribute

I considered this! The main advantage, to my mind, is clear, type-level documentation of how to use the SDK. The drawback, though, is that different auth libraries return differently typed objects, so that'd be putting the burden on the client (at least usually, if we choose one of those types to bless, or always if we make a novel type):

- simple-oauth2 has an [`AccessToken` type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/simple-oauth2/index.d.ts#L58) that you deconstruct with `token.token.access_token`
- client-oauth2 has a [`Token` type](https://github.com/mulesoft-labs/js-client-oauth2/blob/68d2a71565641d321148798d7df9d78a3182e584/index.d.ts#L61) that you deconstruct with `token.accessToken`
- angular-oauth2-oidc gives you [an injectible `OAuthStorage` object](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/additional-documentation/working-with-httpinterceptors.html) that you can get the token out of with `this.authStorage.getItem('access_token')`

It's not obvious to me that that's a worthwhile tradeoff to make, and right now I still think simple `string` arguments would be better, but if I misunderstood your suggestion or are undervaluing the benefit, I'd love to hear more, @slifty!

**Comment by slifty** [comment]
Very belated reply (though it seems this hasn't been implemented yet so not too late!)

The main reason I could think of for having our type (even if that type has a single "token" attribute that is a string) instead of just a string is that it allows for more flexible shapes types down the line without changing the function signature.

For instance, with a type instead of string we could some day support *all of the above* by having an Authentication type with various optional fields and built in shims that get triggered depending on which field is populated and it wouldn't impact users who are just passing the string.

For now the type would just be:

```
type Authentication {
  token: string,
}
```

**Comment by slifty** [comment]
Side note: regardless of approach, I think this ultimately means that there's nothing to "implement" when it comes to authentication, right?  I suppose if we decide to define a type that would be a code action, but otherwise @kavyasukumar you could just add documentation to the appropriate place and close the issue I think.

**Comment by jasonaowen** [comment]
Interesting idea! That kind of future proofing would definitely be nice, although I remain concerned about how building the `Authentication` object would work in practice - seems likely to be painful.

I think we could still get the benefit you're talking about, when the time comes, with either a type alias or just a direct sum type. Something like:

```diff
-const example = (token: string) => ();
+interface AuthenticationToken { accessToken: string; }
+const example = (token: string | AuthenticationToken) => ();
```

Expanding the allowed types for a parameter should always be backwards-compatible, I think.

Doing so consistently would probably benefit from a type alias, though, so we can do it all in one go:

```typescript
// now
type Authentication = string;
// later
type Authentication = string | AuthenticationToken;
```

**Comment by slifty** [comment]
I'm going to close out this issue because it turns out implementing authentication is going to be very easy based on the decisions made in this discussion!

Auth token will be managed by the SDK user; the SDK will simply need to utilize it to create an `Auth: Bearer XXXXXXXX` header.

**Comment by kfogel** [comment]
Ship it!  :100:
