### ISSUE TITLE
Support folder deletion

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/permanent-sdk#34]
The SDK needs to support the deletion of existing folders in an archive.  This might be through a `deleteFolder` function.

There is some discussion of disallowing SFTP deletion within certain archives; I think that will be an SFTP implementation (and that the SDK wouldn't have that restriction; it would be the tools implementing the SDK that should pay attention to those settings)

**Comment by Fenn-CS** [comment]
This is related to [#230](https://github.com/PermanentOrg/back-end/issues/230) in the [back-end repo](https://github.com/PermanentOrg/back-end)

https://github.com/PermanentOrg/back-end/issues/230
