### ISSUE TITLE
Maintain treeshaking structure (`isRecordStatus` should enter its own file?)

### ISSUE THREAD

**Issue by Fenn-CS** [PermanentOrg/permanent-sdk#38]
This is a follow up discussion from #28 about how we could possible do things and how we do them. For now, there is already a potential deviation from the pattern in how we do this which referenced in the quoted comment below.

> Either way, the "one utility per file" IS the pattern we have today; what do you think of creating an issue for that refactoring where we can discuss what's best at that time instead of trying to overhaul utility organization in this PR?

That's reasonable. I should mention that I started "breaking that pattern" in https://github.com/PermanentOrg/permanent-sdk/blob/main/src/utils/generateEnumTypeguard.ts where instead of adding an extra `isRecordStatus.ts` just like with the now deleted [isThumbnailStatus](https://github.com/PermanentOrg/permanent-sdk/commit/bbf5e7d7ae76ad1cc48c83748b36522eb6a6fb99#diff-3fd8b0fd57e8c162d8d0414ed15aef21ee36a9aeb2bf4a833d5260a2969453d7) I threw all of that into `generateEnumTypeguard.ts` perhaps it may be worth while renaming such a file to reflect or filing a PR get things back in line with the correct way of doing things. 

I would open an issue for that discussion. 

What do you think about the service class idea here though?

cc: @slifty

_Originally posted by @Fenn-CS in https://github.com/PermanentOrg/permanent-sdk/issues/28#issuecomment-1180881904_

**Comment by slifty** [comment]
(In this case by the way I think it's best to put typeguards along side types -- so they wouldn't be a utility function they would just be imported from the types.)

**Comment by Fenn-CS** [comment]
Thanks @slifty following #39 and the discussions above, I would now close this.
