### ISSUE TITLE
Implement archive access

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/permanent-sdk#4]
Once we have an authenticated session we need to be able to `getArchive` and `getArchives` for a given user.

I believe this will involve the definition of a few TypeScript types:

* `ArchiveVO` -- this is the VO returned by the PHP api, for internal use within the SDK.
* `Archive` -- this is the exposed "archive" type that the SDK will return (and accept) for various archive methods.

as well as the following exposed SDK methods:

* `getArchives` - returns a list of populated archives (takes token)
* `getArchive` - returns a populated archive (takes token + archive ID)

A little more context can be found in [our SDK thoughts notes](https://pad.opentechstrategies.com/p/permanent-sdk-thoughts)

**Comment by slifty** [comment]
Let's talk about the archive object!

Here are the attributes that the [PHP ArchiveVO contains](https://github.com/PermanentOrg/back-end/blob/be63d67417b6fe6ed57510e882e48ea6bca9a225/library/base/vo/base.archive.vo.php#L14-L29):

* archiveId
* publicDT
* archiveNbr
* public
* view
* viewProperty
* thumbArchiveNbr
* imageRatio
* type
* thumbStatus
* thumbURL200
* thumbURL500
* thumbURL1000
* thumbURL2000
* thumbDT
* tatus

I'm going to try to figure out what each of these actually is and determine better types / structure and where / how they're used.  The questions I'm exploring right now:

1. What is the "public date time" used for (`publicDT`)?
2. What's the difference between an "archive ID" and an "archive number" (`archiveNbr`)?
3. What is `public`?
4. What is `view` and `viewProperty`?
5. What is `thumbArchiveNbr`?
6. What does `type` refer to and what are the possible values?
7. What are the possible values for `thumbStatus`?
8. What is a `thumbDT` and what is it used for?
9. What are the possible values for `status`?

**Comment by slifty** [comment]
The various type values / possible values are defined in the [constants definition](https://github.com/PermanentOrg/back-end/blob/main/library/definition/perm.constants.php).

Specifically:

> What does type refer to and what are the possible values?

https://github.com/PermanentOrg/back-end/blob/be63d67417b6fe6ed57510e882e48ea6bca9a225/library/definition/perm.constants.php#L411-L414

> What are the possible values for status?

https://github.com/PermanentOrg/back-end/blob/be63d67417b6fe6ed57510e882e48ea6bca9a225/library/definition/perm.constants.php#L320-L328

> What are the possible values for thumb status

Same as status, though it looks like the ONLY time anything is ever set is:

https://github.com/PermanentOrg/back-end/blob/be63d67417b6fe6ed57510e882e48ea6bca9a225/api/core/archive/bo/archive.bo.php#L209

so... it's unclear if this is a useful field.

**Comment by cecilia-donnelly** [comment]
I can help with `public` and `publicDT` because I looked into this recently for Kaitlyn:

-     There is a public field on the archive table that is either 0 (private) or 1 (public) (i.e. a  MySQL boolean).  When I tested locally, this flipped from private to public as soon as I uploaded something to the Public workspace.
-     There is also a publicDT field on archive, but unfortunately it looks like it is an exact match for createdDT, except for a few very old archives.  I think we used to use this to indicate when an archive was made public (which would make sense) but that got lost along the way.

**Comment by slifty** [comment]
It looks like archive `view` and `viewProperty` are not used *anywhere*

The Folder VO also has a `view` field which seems to relate to [various folder view types](https://github.com/PermanentOrg/back-end/blob/be63d67417b6fe6ed57510e882e48ea6bca9a225/library/definition/perm.constants.php#L156-L172) (e.g. grid, timeline, etc).

I'm not seeing any instance of `viewProperty` being used or assigned a value; not clear if it does anything in any context.

**Comment by slifty** [comment]
I'm going to assume `thumbDT` references the creation date of the thumbnail, so that's what I'll translate it to.

**Comment by cecilia-donnelly** [comment]
I find `archiveNbr` extremely confusing and have never fully investigated it.  A few things I do know:
- it is a string, not a number
- records/folders also have `archiveNbr`s.  I think they are used to find the folder a record is in, sometimes, though we also have `folder_link` so I'm not totally sure.
- The `archiveNbr` is used to create the link to a public archive (e.g. https://www.permanent.org/p/archive/03dg-0000 - the archive number for mine is '03dg-0000')

**Comment by mithuna** [comment]
So an archiveId is the ID of an archive. An archive can have multiple multiple files. ArchiveNbr in increasing increments is a number used to identify every file on the archive.. So lets say if the archive has an archiveNbr abcd-0000, then the records in this archive will be abcd-0001,abcd-0002..... etc
These archiveNbrs are appended in the URL of each file fetched and inorder to avoid exposing archiveIds to the world, they came up with ArchiveNbr(way before me).

**Comment by slifty** [comment]
I had included the concept of a `displayDate` in the `Archive` type but I'm actually not seeing... why!

I'm going to remove it from the `Archive` type.  (we still store createdAt / updatedAt).  I think in my mind it was going to host the value for `publicDT` but as discussed above that is kind of an obsolete field and we don't need to carry it forward.  Obviously we can add it back if we decide it's useful.

**Comment by slifty** [comment]
I just spoke with @meisekimiu about the question of having a single "children" vs splitting into "folders" and "items" -- the original draft had a single "children" but in runtime this is going to be a huge pain since it forces our users to check / type guard which type the field is.

By splitting into two we keep meaningful information about the children, so I'm going to move to that approach.  It's very easy to combine the two types into one list if the user wants that!

**Comment by slifty** [comment]
As a further followup -- it seems that archives don't technically have children (even though the Vo has elements that indicate they would)

Instead they have a root (which is *not* provided as part of the archive API response)  I'm going to create an issue in backend exploring the merit of having this be part of the archive object, but in the short term I think this just means removing child elements from the `Archive` type.
