### ISSUE TITLE
Oh no, Record is already a thing

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/permanent-sdk#47]
TypeScript has a built in concept of [Record](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) built into the language.  Unfortunately the Permanent backend uses the term `Record` to represent a file in the permanent system.

For the API interaction we're OK because it's actually not `Record` but `RecordVo`.  However, we're going to need to think of something else for our sdk side that isn't just `Record`.

Some ideas:

1. `PermanentRecord` <-- ugh.
2. `File` (this could be confusing since we have `FileVo` which is... different than `RecordVo` somehow)
3. `Item` <-- this has the same downside of `File` while also being very generic.
4. `Document`

Nothing's perfect.  I think `File` might be our best bet (as a partner to `Folder`).  I'm 99% sure that we're merging `RecordVo` and `FileVo` anyway; and if we need to keep track of whatever `FileVo` means we can think of a more specific name for the sdk (e.g. `FileInstance` or `FileVersion` or something).

Any thoughts?

**Comment by meisekimiu** [comment]
I'm fine with `File` since we've discussed before that `Record` is initially a kind of confusing name. But I also agree with the fact that it can cause even more confusion with the whole `FileVO` vs `RecordVO` situation. If we're planning from never even exposing the `FileVO` type to the user to begin with, I think `File` is the best name.

**Comment by Fenn-CS** [comment]
I agree with @meisekimiu.

**Comment by slifty** [comment]
I've stewed for a while and here's where i'm landing:

`Record` should be `File`
`File` should be `Derivative`

(`Files` have file `Derivatives`)

**Comment by slifty** [comment]
Happy new year!

Following up -- [derivative](https://www.digitizationguidelines.gov/term.php?term=derivativefile) is a term of art in archival so I want to be careful.  In fact some of these files ARE derivatives from an archival perspective, but some of them are not.

Given that I'm leaning back to having `Record` just be `Item` (and an `Item` has `Files`, which have a `DerivativeType` -- which itself might be slightly inaccurate since technically `original` is not a *derivative* type but, so it goes)
