### ISSUE TITLE
Can we be agnostic about HTTP libraries?

### ISSUE THREAD

**Issue by jasonaowen** [PermanentOrg/permanent-sdk#5]
If reasonably possible, I think it would be good for this SDK to not explicitly depend on any particular library for making HTTP requests. The old SDK uses [axios](https://www.npmjs.com/package/axios), and that is a fine choice, but it makes it less suitable for use in, say, Angular applications. The [next major version of Node will include support for `fetch`](https://fusebit.io/blog/node-fetch/), but if we want to support current LTS versions of Node, we won't be able to reliably use that until 2024.

Is there a way for us to be agnostic about HTTP libraries? Can we accept some kind of argument somewhere that makes requests and returns results in a known and expected way? If so, is such an approach worth the additional complexity?

**Comment by jasonaowen** [comment]
After 20 minutes of research, I don't see any clear choices; this is not obviously a pattern that exists in the Node ecosystem. I'll leave this open for the rest of the team to consider, but it's quite possible that this idea is not practical.

**Comment by slifty** [comment]
Since we're using node fetch I think I'll close this issue for now -- we can re-visit when we move to Node 18 and want to drop support for Node 16!
