### ISSUE TITLE
My Files has no `displayDT`

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/permanent-sdk#69]
I just had an issue where my local server started returning an archive root folder (`My Files`) with a `null` for `displayDT`.

Our type expects displayDT to always be present, so this resulted in an error.

I don't know how the backend got into that state.  This means either the sdk's assumptions about displayDT are incorrect / it CAN be null, or there is a backend bug.

For now I may change the type to allow null -- however, this would mean the SDK would populate the display time as `now()` when the situation comes up and I'm not actually sure we want that.

**Comment by slifty** [comment]
@cecilia-donnelly or @meisekimiu, do you know if displayDT should be safely assumed to be populated by the SDK?  If so I'd probably prefer close this issue and instead open a back-end bug report.

**Comment by liam-lloyd** [comment]
The `displayDT` columns of both the `folder` and `record` tables are nullable, so I'd say it's not safe to assume they're populated (I don't know whether we actually _intend_ for them to ever be `NULL` though).
